[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "hackathon-fft"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.6.0.dev2025081405,<26"
