#!/usr/bin/env bash
# NVIDIA-only: discover a system ptxas and write fft/.nvidia-gpu-env for pixi
# activation. Needed for Pre-Turing NVIDIA GPUs and drivers older than 580.
# AMD / Apple Silicon / CPU-only machines should not run this — it is a no-op
# outside NVIDIA. See Modular GPU requirements / MODULAR_NVPTX_COMPILER_PATH.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PROJECT_ROOT}/.nvidia-gpu-env"

has_nvidia_gpu() {
  if command -v nvidia-smi >/dev/null 2>&1; then
    # Succeeds when at least one NVIDIA GPU is visible to the driver.
    nvidia-smi -L >/dev/null 2>&1
    return $?
  fi
  # Fallback when nvidia-smi is missing but a device node exists.
  compgen -G '/dev/nvidia[0-9]*' >/dev/null 2>&1
}

if ! has_nvidia_gpu; then
  cat <<'EOF'
No NVIDIA GPU detected (nvidia-smi / /dev/nvidia*).

MODULAR_NVPTX_COMPILER_PATH is an NVIDIA/CUDA unlock only. AMD, Apple Silicon,
and CPU-only setups do not need this script — Mojo/MAX use other backends
there. Nothing was written.
EOF
  exit 0
fi

resolve_ptxas() {
  if [[ -n "${MODULAR_NVPTX_COMPILER_PATH:-}" && -x "${MODULAR_NVPTX_COMPILER_PATH}" ]]; then
    printf '%s\n' "${MODULAR_NVPTX_COMPILER_PATH}"
    return 0
  fi

  local candidates=(
    /usr/local/cuda/bin/ptxas
  )
  # Prefer highest-numbered CUDA toolkit installs when several exist.
  local cuda_ptxas
  for cuda_ptxas in $(ls -1d /usr/local/cuda-*/bin/ptxas 2>/dev/null | sort -V -r); do
    candidates+=("${cuda_ptxas}")
  done

  local path
  for path in "${candidates[@]}"; do
    if [[ -x "${path}" ]]; then
      printf '%s\n' "${path}"
      return 0
    fi
  done

  if command -v ptxas >/dev/null 2>&1; then
    command -v ptxas
    return 0
  fi

  return 1
}

if ! PTXAS_PATH="$(resolve_ptxas)"; then
  cat >&2 <<'EOF'
error: NVIDIA GPU is present but no executable ptxas was found.

Install a CUDA Toolkit that provides ptxas (compatible with your GPU/driver),
then re-run: pixi run enable-nvidia-gpu

Example locations Modular documents:
  /usr/local/cuda/bin/ptxas
EOF
  exit 1
fi

# Normalize to an absolute path.
PTXAS_PATH="$(cd "$(dirname "${PTXAS_PATH}")" && pwd)/$(basename "${PTXAS_PATH}")"

{
  printf '# Generated by scripts/enable-nvidia-gpu.sh — do not commit.\n'
  printf '# NVIDIA-only: MODULAR_NVPTX_COMPILER_PATH (CUDA ptxas unlock).\n'
  printf 'export MODULAR_NVPTX_COMPILER_PATH=%q\n' "${PTXAS_PATH}"
} >"${ENV_FILE}"

# Drop the old generic filename if a previous revision left one behind.
rm -f "${PROJECT_ROOT}/.gpu-env"

cat <<EOF
Wrote ${ENV_FILE}
  MODULAR_NVPTX_COMPILER_PATH=${PTXAS_PATH}

ptxas --version:
$("${PTXAS_PATH}" --version 2>&1 | sed 's/^/  /')

Next steps:
  1. New pixi shells / \`pixi run\` tasks will source .nvidia-gpu-env via activation.
  2. If you already hit a CUDA 13 / driver-block failure, clear Mojo caches
     once so stale CUBINs are not reused, e.g.:
       rm -rf ~/.modular/cache
       # or: pixi clean
  3. Re-run: pixi run tests
EOF
